services:
 app:
   restart: unless-stopped
   container_name: coinflow
   network_mode: "host"
   build: .
   ports:
     - '3000:3000'
 mongo:
   container_name: mongodb
   restart: unless-stopped
   image: mongo:latest
   volumes:
     - mongodb_data:/var/db
   ports:
     - '27017:27017' 
volumes:
  mongodb_data:
    external: false
